version: '3'

services:
  django:
    build:
      dockerfile: ./docker/gwcloud_bilby.Dockerfile
      context: .
      target: django-runner
    container_name: gwcloud_bilby_django
    env_file: .env
    ports:
      - "8000"
    depends_on:
      - db


  static:
    build:
      dockerfile: ./docker/gwcloud_bilby.Dockerfile
      context: .
      target: static-runner
    container_name: gwcloud_bilby_static
    ports:
      - "8000:8000"
    depends_on:
      - django

  db:
    image: mysql:8.4.3
    container_name: gwcloud_bilby_mysql
    env_file: .env
    volumes:
      - ./db:/var/lib/mysql
