<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'DjangoJestLintEngine' => 'lint/engine/DjangoJestLintEngine.php',
    'DjangoJestUnitTestEngine' => 'unit/DjangoJestUnitTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'DjangoJestLintEngine' => 'ArcanistLintEngine',
    'DjangoJestUnitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
