apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gwcloud-bilby-db
  name: gwcloud-bilby-db
  namespace: gwcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        io.kompose.service: gwcloud-bilby-db
  template:
    metadata:
      labels:
        io.kompose.service: gwcloud-bilby-db
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: bilby
          image: mysql:5.7
          name: mysql-gwcloud-bilby
          resources: {}
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: bilby
              mountPath: "/var/lib/mysql"
      volumes:
        - name: bilby
          persistentVolumeClaim:
            claimName: bilby
      restartPolicy: Always
