kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gwcloud-bilby-nfs-job-data-pvc
  namespace: gwcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  selector:
    matchLabels:
      volume: gwcloud-bilby-nfs-job-data-pv
