---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-bilby-django
  namespace: gwcloud
  labels:
    name: gwcloud-bilby-django
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-bilby-django
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-bilby-django
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: bilby
            - secretRef:
                name: common
          name: gwcloud-bilby-django
          image: nexus.gwdc.org.au/docker/gwcloud_bilby_django:0.65
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
          volumeMounts:
            - name: gwcloud-bilby-nfs-job-data
              mountPath: "/job_data/"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: gwcloud-bilby-nfs-job-data
          persistentVolumeClaim:
            claimName: gwcloud-bilby-nfs-job-data-pvc
... 
