# Generated by Django 2.2.12 on 2020-05-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilby', '0005_auto_20200508_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prior',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prior', to='bilby.BilbyJob'),
        ),
    ]
