# Generated by Django 2.2.12 on 2020-05-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilby', '0007_auto_20200512_0126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bilbyjob',
            unique_together={('user_id', 'name')},
        ),
        migrations.RemoveField(
            model_name='bilbyjob',
            name='username',
        ),
    ]
