# Generated by Django 2.2.12 on 2020-05-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilby', '0007_auto_20200512_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilbyjob',
            old_name='public',
            new_name='private',
        ),
    ]
