# Generated by Django 2.2.12 on 2020-05-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilby', '0008_auto_20200514_0204'),
        ('bilby', '0009_auto_20200513_0552'),
    ]

    operations = [
    ]
