# Generated by Django 2.2.14 on 2021-05-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilby', '0013_bilbyjob_ini_string'),
        ('bilby', '0013_auto_20210321_2322'),
    ]

    operations = [
    ]
