# Generated by Django 2.2.12 on 2020-05-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0008_auto_20200508_0830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataparameter",
            name="name",
            field=models.CharField(
                choices=[
                    ["hanford", "Hanford"],
                    ["livingston", "Livingston"],
                    ["virgo", "Virgo"],
                    ["signal_duration", "Signal Duration (s)"],
                    ["sampling_frequency", "Sampling Frequency (Hz)"],
                    ["trigger_time", "Trigger Time"],
                    ["hanford_minimum_frequency", "Hanford Minimum Frequency"],
                    ["hanford_maximum_frequency", "Hanford Maximum Frequency"],
                    ["hanford_channel", "Hanford Channel"],
                    ["livingston_minimum_frequency", "Livingston Minimum Frequency"],
                    ["livingston_maximum_frequency", "Livingston Maximum Frequency"],
                    ["livingston_channel", "Livingston Channel"],
                    ["virgo_minimum_frequency", "Virgo Minimum Frequency"],
                    ["virgo_maximum_frequency", "Virgo Maximum Frequency"],
                    ["virgo_channel", "Virgo Channel"],
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="signalparameter",
            name="name",
            field=models.CharField(
                choices=[
                    ["mass1", "Mass 1"],
                    ["mass2", "Mass 2"],
                    ["luminosity_distance", "Luminosity Distance (Mpc)"],
                    ["iota", "iota"],
                    ["psi", "psi"],
                    ["phase", "Phase"],
                    ["merger_time", "Merger Time (GPS Time)"],
                    ["ra", "Right Ascension (Radians)"],
                    ["dec", "Declination (Degrees)"],
                ],
                max_length=50,
            ),
        ),
    ]
