# Generated by Django 2.2.14 on 2021-05-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0012_insert_default_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilbyjob',
            name='ini_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
