# Generated by Django 2.2.19 on 2021-06-01 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0015_insert_preferred_label"),
        ("bilbyui", "0014_merge_20210527_0404"),
    ]

    operations = []
