# Generated by Django 3.2.3 on 2021-06-03 01:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("bilbyui", "0017_pull_ini_files"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bilbyjob",
            table=None,
        ),
        migrations.AlterModelTable(
            name="data",
            table=None,
        ),
        migrations.AlterModelTable(
            name="dataparameter",
            table=None,
        ),
        migrations.AlterModelTable(
            name="label",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prior",
            table=None,
        ),
        migrations.AlterModelTable(
            name="sampler",
            table=None,
        ),
        migrations.AlterModelTable(
            name="samplerparameter",
            table=None,
        ),
        migrations.AlterModelTable(
            name="signal",
            table=None,
        ),
        migrations.AlterModelTable(
            name="signalparameter",
            table=None,
        ),
    ]
