# Generated by Django 3.2.3 on 2021-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0020_parse_ini_kv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilbyjob',
            name='ini_string',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
