# Generated by Django 3.2.3 on 2021-06-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0021_alter_bilbyjob_ini_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataparameter',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dataparameter',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='prior',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prior',
            name='job',
        ),
        migrations.RemoveField(
            model_name='sampler',
            name='job',
        ),
        migrations.RemoveField(
            model_name='samplerparameter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='samplerparameter',
            name='sampler',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='job',
        ),
        migrations.RemoveField(
            model_name='signalparameter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='signalparameter',
            name='signal',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='DataParameter',
        ),
        migrations.DeleteModel(
            name='Prior',
        ),
        migrations.DeleteModel(
            name='Sampler',
        ),
        migrations.DeleteModel(
            name='SamplerParameter',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
        migrations.DeleteModel(
            name='SignalParameter',
        ),
    ]
