# Generated by Django 3.2.4 on 2021-06-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0023_filedownloadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilbyjob',
            name='is_uploaded_job',
            field=models.BooleanField(default=False),
        ),
    ]
