# Generated by Django 3.2.9 on 2022-01-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0027_alter_bilbyjob_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventid",
            name="is_ligo_event",
            field=models.BooleanField(default=False),
        ),
    ]
