# Generated by Django 3.2.12 on 2022-03-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0029_supportingfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilbyjob",
            name="cluster",
            field=models.TextField(null=True),
        ),
    ]
