# Generated by Django 3.2.12 on 2022-03-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0030_bilbyjob_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportingfile',
            old_name='token',
            new_name='upload_token',
        ),
    ]
