# Generated by Django 3.2.12 on 2022-03-03 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0031_rename_token_supportingfile_upload_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportingfile",
            name="download_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
