# Generated by Django 3.2.13 on 2022-08-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0032_supportingfile_download_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilbyjob',
            options={'ordering': ('last_updated', 'name')},
        ),
        migrations.AlterField(
            model_name='bilbyjob',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
