# Generated by Django 3.2.13 on 2022-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyui', '0033_auto_20220810_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilbyjob',
            options={'ordering': ('-last_updated', 'name')},
        ),
        migrations.AddField(
            model_name='eventid',
            name='gps_time',
            field=models.FloatField(default=1126259462.391),
        ),
    ]
