# Generated by Django 3.2.19 on 2023-06-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0038_rename_is_uploaded_job_bilbyjob_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inikeyvalue",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
