# Generated by Django 3.2.19 on 2023-06-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bilbyui", "0039_inikeyvalue_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bilbyjob",
            name="ini_string",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
