# Generated by Django 5.2.15 on 2026-08-03 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilbyui", "0042_convert_user_id_to_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bilbyjob",
            name="gwflow_analysis_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="GWFlowJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "schema_version",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("libraries", models.JSONField(blank=True, default=list)),
                (
                    "current_history_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "current_history_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ligo_only", models.BooleanField(default=True)),
                ("is_pruned", models.BooleanField(db_index=True, default=False)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bilbyui.eventid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gwflow_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_updated", "sname"),
            },
        ),
        migrations.AddField(
            model_name="bilbyjob",
            name="gwflow_job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bilby_jobs",
                to="bilbyui.gwflowjob",
            ),
        ),
        migrations.CreateModel(
            name="GWFlowFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_uid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("path", models.TextField()),
                ("file_name", models.TextField()),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "md5_sum",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("uploaded", models.BooleanField(db_index=True, default=False)),
                (
                    "download_token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="bilbyui.gwflowjob",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "analysis_uid", "path")},
            },
        ),
    ]
