# Generated by Django 5.2.15 on 2026-09-28 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilbyui", "0044_gwflow_portal_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventid",
            name="event_id",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be of the form GW123456_123456, GW123456, or G123456",
                        regex="^(GW\\d{6}(_\\d{6})?|G\\d+)$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventid",
            name="trigger_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be of the form S123456a or G123456",
                        regex="^(S\\d{6}[a-z]{1,2}|G\\d+)$",
                    )
                ],
            ),
        ),
    ]
