# Generated by Django 5.2.15 on 2026-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilbyui", "0045_alter_eventid_event_id_alter_eventid_trigger_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilbyjob",
            name="trigger_time",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="gwflowjob",
            name="trigger_time",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventid",
            name="gps_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
