# Generated by Django 5.2.17 on 2026-10-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bilbyui", "0046_bilbyjob_trigger_time_gwflowjob_trigger_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bilbyjob",
            name="is_ligo_job",
        ),
        migrations.RemoveField(
            model_name="eventid",
            name="is_ligo_event",
        ),
        migrations.RemoveField(
            model_name="gwflowjob",
            name="ligo_only",
        ),
    ]
