---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bilby
  labels:
    volume: bilby
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.12
    path: "/mnt/sharedfolder/gwcloud/bilby/db"
...
