import json
import os

MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_ROOT_PASSWORD = os.getenv("MYSQL_ROOT_PASSWORD")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")

SECRET_KEY = os.getenv("SECRET_KEY")
JOB_CONTROLLER_JWT_SECRET = os.getenv("JOB_CONTROLLER_JWT_SECRET")
AUTH_SERVICE_JWT_SECRET = os.getenv("AUTH_SERVICE_JWT_SECRET")
ELASTIC_SEARCH_API_KEY = os.getenv("ELASTIC_SEARCH_API_KEY")

GWOSC_INGEST_USER = int(os.getenv("GWOSC_INGEST_USER"))

PERMITTED_EVENT_CREATION_USER_IDS = json.loads(
    os.getenv("PERMITTED_EVENT_CREATION_USER_IDS")
)

EMBARGO_START_TIME = os.getenv("EMBARGO_START_TIME")

CLUSTERS = json.loads(os.getenv("CLUSTERS"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": MYSQL_DATABASE,
        "HOST": MYSQL_HOST,
        "USER": MYSQL_USER,
        "PORT": 3306,
        "PASSWORD": MYSQL_PASSWORD,
    },
}
