SIMULATED = ["simulated", "Simulated"]
OPEN = ["open", "Open"]

HANFORD = ["hanford", "Hanford"]
LIVINGSTON = ["livingston", "Livingston"]
VIRGO = ["virgo", "Virgo"]
SIGNAL_DURATION = ["signal_duration", "Signal Duration (s)"]
SAMPLING_FREQUENCY = ["sampling_frequency", "Sampling Frequency (Hz)"]
TRIGGER_TIME = ["trigger_time", "Trigger Time"]
HANFORD_MIN_FREQ = ["hanford_minimum_frequency", "Hanford Minimum Frequency"]
HANFORD_MAX_FREQ = ["hanford_maximum_frequency", "Hanford Maximum Frequency"]
HANFORD_CHANNEL = ["hanford_channel", "Hanford Channel"]
LIVINGSTON_MIN_FREQ = ["livingston_minimum_frequency", "Livingston Minimum Frequency"]
LIVINGSTON_MAX_FREQ = ["livingston_maximum_frequency", "Livingston Maximum Frequency"]
LIVINGSTON_CHANNEL = ["livingston_channel", "Livingston Channel"]
VIRGO_MIN_FREQ = ["virgo_minimum_frequency", "Virgo Minimum Frequency"]
VIRGO_MAX_FREQ = ["virgo_maximum_frequency", "Virgo Maximum Frequency"]
VIRGO_CHANNEL = ["virgo_channel", "Virgo Channel"]

SKIP = ["skip", "None"]
BBH = ["binaryBlackHole", "Binary Black Hole"]
BNS = ["binaryNeutronStar", "Binary Neutron Star"]

PRIOR_4S = ["4s", "4s"]
PRIOR_8S = ["8s", "8s"]
PRIOR_16S = ["16s", "16s"]
PRIOR_32S = ["32s", "32s"]
PRIOR_64S = ["64s", "64s"]
PRIOR_128S = ["128s", "128s"]

MASS1 = ["mass1", "Mass 1"]
MASS2 = ["mass2", "Mass 2"]
LUMINOSITY_DISTANCE = ["luminosity_distance", "Luminosity Distance (Mpc)"]
IOTA = ["iota", "iota"]
PSI = ["psi", "psi"]
PHASE = ["phase", "Phase"]
MERGER = ["merger_time", "Merger Time (GPS Time)"]
RA = ["ra", "Right Ascension (Radians)"]
DEC = ["dec", "Declination (Degrees)"]

FIXED = ["fixed", "Fixed"]
UNIFORM = ["uniform", "Uniform"]

DYNESTY = ["dynesty", "Dynesty"]
NESTLE = ["nestle", "Nestle"]
EMCEE = ["emcee", "Emcee"]
 